name: Erlang CI
on: push
jobs:
  Lint:
    strategy:
      matrix:
        erlang: ['24', '26']
    runs-on: ubuntu-latest
    container:
      image: erlang:${{ matrix.erlang }}
    steps:
    - name: Clone Elvis linter project
      uses: actions/checkout@v3
      with:
        repository: AntoineGagne/elvis
    - name: Install Elvis (linter)
      run: |
        mkdir -p ~/bin
        rebar3 escriptize
        mv _build/default/bin/elvis ~/bin
        echo "~/bin" >> "$GITHUB_PATH"
    - name: Clone project
      uses: actions/checkout@v3
    - name: Run Linter
      run: make elvis
  Test:
    strategy:
      matrix:
        erlang: ['24', '26']
    runs-on: ubuntu-latest
    container:
      image: erlang:${{ matrix.erlang }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        env:
          cache-name: rebar3
        with:
          path: |
            _build
            ~/.cache/rebar3
          key: ci-${{runner.os}}-${{env.cache-name}}-erlang_${{matrix.erlang}}-rebar3-${{hashFiles('rebar.lock')}}
      - name: tests
        run: make test