name: Erlang CI
on: push
jobs:
  Test:
    strategy:
      matrix:
        erlang: ['24']
    runs-on: ubuntu-latest
    container:
      image: erlang:${{ matrix.erlang }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        env:
          cache-name: rebar3
        with:
          path: |
            _build
            ~/.cache/rebar3
          key: ci-${{runner.os}}-${{env.cache-name}}-erlang_${{matrix.erlang}}-rebar3-${{hashFiles('rebar.lock')}}
      - name: tests
        run: make test